import React from "react";

const packages = [
  {
    category: "E-Commerce",
    price: "$999",
    title: "E-commerce-website",
    features: [
      "E-Commerce Website Design and Development",
      "Theme Based Design",
      "2 Banner Designs",
      "Sliding Banner",
      "3 Stock Photos",
      "06 Revisions",
      "Hover Effects",
      "Up to 10 Products",
      "Up to 3 Categories",
      "Content/Inventory Management System",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax calculator Integration",
      "Shipping calculator Integration",
      "Wishlist",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    category: "E-Commerce",
    price: "$1399",
    title: "E-commerce-startup",
    features: [
      "E-Commerce Website Design and Development",
      "High-end Theme Based Design",
      "5 Banner Designs",
      "Sliding Banner",
      "5 Stock Photos",
      "12 Revisions",
      "Hover Effects",
      "Up to 25 Products",
      "Up to 5 Categories",
      "Content/Inventory Management System",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Shipping calculator Integration",
      "Wishlist",
      "Search Engine Submission",
      "Social Media Pages Integration",
      "Facebook “Like” Plugin integration",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
    ],
  },
  {
    category: "E-Commerce",
    price: "$2399",
    title: "E-commerce-professional",
    features: [
      "E-Commerce Website Design and Development",
      "Customized Theme Based Design",
      "7 Banner Designs",
      "Sliding Banner",
      "7 Stock Photos",
      "Unlimited Revisions",
      "Hover Effects",
      "Up to 100 Products",
      "Up to 10 Categories",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax calculator Integration",
      "Shipping calculator Integration",
      "Wishlist",
      "Import/Export Order",
      "Bulk Import/export of Order information",
      "Search Engine Submission",
      "SEO Friendly",
      "Web Analytics Integration",
      "Monthly Traffic Reporting",
      "Social Media Pages Integration",
      "Facebook “Like” Plugin integration",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    category: "E-Commerce",
    price: "$3399",
    title: "E-commerce-Identity",
    features: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Unique Design",
      "10 Banner Designs",
      "Sliding Banner",
      "10 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Up to 500 Products",
      "Up to 25 Categories",
      "Product Reviews & Ratings",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "User Signup Area",
      "User Sign-in Area",
      "User Dashboard Area",
      "Auto Email for Profile Validation & Notification(s)",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax calculator Integration",
      "Shipping calculator Integration",
      "Wishlist",
      "Import/Export Order",
      "Bulk Import/export of Order information",
      "Search Engine Submission",
      "SEO Friendly",
      "Web Analytics Integration",
      "Monthly Traffic Reporting",
      "Social Media Pages Integration",
      "Facebook “Like” Plugin integration",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    category: "E-Commerce",
    price: "$4999",
    title: "E-commerce-Elite",
    features: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Interactive, Dynamic, Unique Design",
      "User-friendly Navigation",
      "20 Banner Designs",
      "Sliding Banner",
      "20 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Reviews & Ratings",
      "Product Summary Reports",
      "Multiple Filtrations Option",
      "Multiple Shorting Options",
      "Product View with Multiple Views",
      "Product Rating",
      "Product Detail with Similar Product Range",
      "Coupon Code Generation",
      "Product Comparison",
      "User Signup Area",
      "User Sign-in Area",
      "User Dashboard Area",
      "Auto Email for Profile Validation & Notification(s)",
      "Last Purchase Order Details",
      "Customer Login via Facebook/Google+",
      "Customer profile management",
      "Discounted Products Showcase",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Multiple Currency Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax calculator Integration",
      "Shipping calculator Integration",
      "Wishlist",
      "Import/Export Order",
      "Bulk Import/export of Order information",
      "Bulk Product Upload From Excel Sheet",
      "Export order into excel sheet",
      "Live Chat Integration",
      "SEO Friendly",
      "Web Analytics Integration",
      "Monthly Traffic Reporting",
      "Social Media Pages Integration",
      "Facebook Shop Setup",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    category: "E-Commerce",
    price: "$7398",
    title: "E-commerce-corporate",
    features: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Interactive, Dynamic, Unique Design",
      "User-friendly Navigation",
      "20 Banner Designs",
      "Sliding Banner",
      "20 Stock Photos",
      "Special Hover Effects",
      "Unlimited Revisions",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Reviews & Ratings",
      "Product Summary Reports",
      "Multiple Filtrations Option",
      "Multiple Shorting Options",
      "Product View with Multiple Views",
      "Product Rating",
      "Product Detail with Similar Product Range",
      "Coupon Code Generation",
      "Product Comparison",
      "User Signup Area",
      "User Sign-in Area",
      "User Dashboard Area",
      "Auto Email for Profile Validation & Notification(s)",
      "Last Purchase Order Details",
      "Customer Login via Facebook/Google+",
      "Customer profile management",
      "Discounted Products Showcase",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Multiple Currency Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax calculator Integration",
      "Shipping calculator Integration",
      "Wishlist",
      "Import/Export Order",
      "Bulk Import/export of Order information",
      "Bulk Product Upload From Excel Sheet",
      "Export order into excel sheet",
      "Live Chat Integration",
      "SEO Friendly",
      "Web Analytics Integration",
      "Monthly Traffic Reporting",
      "Social Media Pages Integration",
      "Facebook Shop Setup",
      "Facebook “Like” Plugin integration",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "Money Back Guarantee *",
      "Unlimited Revisions",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
];

const PackagesTailwind = () => {
  return (
    <div className="py-12 px-4 text-center bg-gray-100">
      <h2 className="text-3xl text-black font-bold mb-2">
        Most Affordable Packages
      </h2>
      <p className="text-gray-600 mb-10">
        We are well aware of the competition. That is the reason why we have a
        fair pricing model. <br />
        We ensure quality over quantity on each order.
      </p>

      <div className="flex flex-wrap justify-center gap-6">
        {packages.map((pkg, idx) => (
          <div
            key={idx}
            className="bg-gradient-to-b from-sky-400 to-sky-600 text-white rounded-xl w-80 p-6 shadow-lg flex flex-col justify-between"
          >
            <div>
              <div className="text-4xl font-bold mb-2">{pkg.price}</div>
              <div className="text-xl font-medium capitalize mb-4">
                {pkg.title}
              </div>
              <hr className="border-white border-opacity-30 mb-4" />
              <ul className="text-left space-y-2 max-h-56 overflow-y-auto pr-2 text-sm">
                {pkg.features.map((feature, i) => (
                  <li key={i} className="flex items-start">
                    <span className="text-white mr-2 mt-1">✓</span>
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="mt-6 space-y-2">
              <button className="w-full bg-white text-sky-600 font-bold py-2 rounded hover:bg-sky-100 transition">
                ORDER NOW
              </button>
              <button className="w-full bg-white text-sky-600 font-bold py-2 rounded hover:bg-sky-100 transition text-sm">
                Click here for <b>Live Chat</b>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default PackagesTailwind;
